export const SEReason = Object.freeze({
   NOT_FOUND: 'NOT_FOUND',

   REQUIRED: 'REQUIRED',
   NOT_ALLOWED: 'NOT_ALLOWED',
   NOT_UNIQUE: 'NOT_UNIQUE',

   NOT_VALID: 'NOT_VALID',
   NOT_STRING: 'NOT_STRING',
   NOT_NUMBER: 'NOT_NUMBER',
   NOT_BOOLEAN: 'NOT_BOOLEAN',

   UNEXPECTED: 'UNEXPECTED',
   MISCONFIGURED: 'MISCONFIGURED'
});