export const SEReason = Object.freeze({
   NOT_UNIQUE: 'NOT_UNIQUE',
   NOT_VALID: 'NOT_VALID',

   MISCONFIGURED: 'MISCONFIGURED',
   METHOD_NOT_IMPLEMENTED: 'METHOD_NOT_IMPLEMENTED',
   UNEXPECTED: 'UNEXPECTED'
});