export const ErrorName = Object.freeze({
    NOT_FOUND: 'NOT_FOUND',
    BAD_REQUEST: 'BAD_REQUEST',
    VALIDATION: 'VALIDATION',
    NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

    SERVER_ERROR: 'SERVER_ERROR',

    UNEXPECTED: 'UNEXPECTED'
});