export const ErrorReason = Object.freeze({
    NOT_FOUND: 'NOT_FOUND',
    VALIDATION:'VALIDATION',
    NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    UNEXPEXTED: 'UNEXPEXTED'
});